open Parser

let pprint_tokens ppf = function
  | LPAREN       -> Fmt.pf ppf "LPAREN@."
  | RPAREN       -> Fmt.pf ppf "RPAREN@."
  | LBRACE       -> Fmt.pf ppf "LBRACE@."
  | RBRACE       -> Fmt.pf ppf "RBRACE@."
  | LBRACK       -> Fmt.pf ppf "LBRACK@."
  | RBRACK       -> Fmt.pf ppf "RBRACK@."
  | COLON        -> Fmt.pf ppf "COLON@."
  | COMMA        -> Fmt.pf ppf "COMMA@."
  | DOT          -> Fmt.pf ppf "DOT@."
  | SEMI         -> Fmt.pf ppf "SEMI@."
  | ARROW        -> Fmt.pf ppf "ARROW@."
  | BEGIN        -> Fmt.pf ppf "BEGIN@."
  | END          -> Fmt.pf ppf "END@."
  | LNAME n      -> Fmt.pf ppf "LNAME(%s)@." (ParsedAst.label_to_string n)
  | UNAME n      -> Fmt.pf ppf "UNAME(%s)@." (ParsedAst.label_to_string n)
  | GNAME n      -> Fmt.pf ppf "GNAME(%s)@." (ParsedAst.label_to_string n)
  | UNDERSCORE   -> Fmt.pf ppf "UNDERSCORE@."
  | AT           -> Fmt.pf ppf "AT@."
  | INT i        -> Fmt.pf ppf "INT(%d)@." i
  | STRING s     -> Fmt.pf ppf "STRING(\"%s\")@." s
  | BOOL true    -> Fmt.pf ppf "BOOL(true)@."
  | BOOL false   -> Fmt.pf ppf "BOOL(false)@."
  | FLOAT f      -> Fmt.pf ppf "FLOAT(%f)@." f
  | IMPORT       -> Fmt.pf ppf "IMPORT@."
  | MODULE       -> Fmt.pf ppf "MODULE@."
  | BREAK        -> Fmt.pf ppf "BREAK@."
  | CONTINUE     -> Fmt.pf ppf "CONTINUE@."
  | RET          -> Fmt.pf ppf "RET@."
  | PRINT        -> Fmt.pf ppf "PRINT@."
  | THIS         -> Fmt.pf ppf "THIS@."
  | NULL         -> Fmt.pf ppf "NULL@."
  | FN           -> Fmt.pf ppf "FN@."
  | IF           -> Fmt.pf ppf "IF@."
  | ELIF         -> Fmt.pf ppf "ELIF@."
  | ELSE         -> Fmt.pf ppf "ELSE@."
  | LET          -> Fmt.pf ppf "LET@."
  | CONST        -> Fmt.pf ppf "CONST@."
  | PUB          -> Fmt.pf ppf "PUB@."
  | REF          -> Fmt.pf ppf "REF@."
  | STATIC       -> Fmt.pf ppf "STATIC@."
  | LOOP         -> Fmt.pf ppf "LOOP@."
  | WHILE        -> Fmt.pf ppf "WHILE@."
  | FOR          -> Fmt.pf ppf "FOR@."
  | IN           -> Fmt.pf ppf "IN@."
  | CLASS        -> Fmt.pf ppf "CLASS@."
  | TRAIT        -> Fmt.pf ppf "TRAIT@."
  | IMPL         -> Fmt.pf ppf "IMPL@."
  | NEW          -> Fmt.pf ppf "NEW@."
  | DEL          -> Fmt.pf ppf "DEL@."
  | EQUAL        -> Fmt.pf ppf "EQUAL@."
  | LARGER       -> Fmt.pf ppf "LARGER@."
  | LEQ          -> Fmt.pf ppf "LEQ@."
  | SMALLER      -> Fmt.pf ppf "SMALLER@."
  | SEQ          -> Fmt.pf ppf "SEQ@."
  | NEQ          -> Fmt.pf ppf "NEQ@."
  | ASSIGN       -> Fmt.pf ppf "ASSIGN@."
  | MUL_ASSIGN   -> Fmt.pf ppf "MUL_ASSIGN@."
  | DIV_ASSIGN   -> Fmt.pf ppf "DIV_ASSIGN@."
  | PLUS_ASSIGN  -> Fmt.pf ppf "PLUS_ASSIGN@."
  | MINUS_ASSIGN -> Fmt.pf ppf "MINUS_ASSIGN@."
  | MOD_ASSIGN   -> Fmt.pf ppf "MOD_ASSIGN@."
  | STAR         -> Fmt.pf ppf "STAR@."
  | DIVIDE       -> Fmt.pf ppf "DIVIDE@."
  | MOD          -> Fmt.pf ppf "MOD@."
  | BAR          -> Fmt.pf ppf "BAR@."
  | AMPER        -> Fmt.pf ppf "AMPER@."
  | PLUS         -> Fmt.pf ppf "PLUS@."
  | MINUS        -> Fmt.pf ppf "MINUS@."
  | NOT          -> Fmt.pf ppf "NOT@."
  | BARBAR       -> Fmt.pf ppf "BARBAR@."
  | AMPERAMPER   -> Fmt.pf ppf "AMPERAMPER@."
  | EOF          -> Fmt.pf ppf "EOF@."
